{caught,throw,my_exception}
